Updates to AMP PD section in datasets tab
DataBiosphere/Saturn-UI pull request #1914
Opened 2019-10-29 22:03 UTC by wnojopra

The upcoming AMP PD release now uses a 2-tiered access model, and there is an updated data explorer for each tier.

![Screenshot from 2019-10-29 15-00-39](https://user-images.githubusercontent.com/6879774/67812680-f6704980-fa5c-11e9-92ca-db33c18454aa.png)

2019-10-29 23:09 UTC, mbookman requested changes

2019-10-29 23:09 UTC, mbookman commented on src/data/datasets.js
> +    origin: 'https://amp-pd-data-explorers.appspot.com',
Please use the public URLs if you can:

- data-explorer.amp-pd.org
- clinical-data-explorer.amp-pd.org

Otherwise LGTM.

Thanks!

2019-10-29 23:39 UTC, mbookman approved these changes
LGTM

2019-10-30 16:56 UTC, panentheos commented on src/data/datasets.js
> +    origin: 'https://data-explorer.amp-pd.org',
There is code in `workspace/Data.js` that looks for the string 'appspot.com' to detect which data explorer it came from. If we're using different URLs here, we might need to change that logic as well.

2019-10-30 17:06 UTC, melissachang commented on src/data/datasets.js
> +    origin: 'https://data-explorer.amp-pd.org',
Good catch. I recommend changing back to appspot. Note that AMP PD users won't see the appspot, they'll see https://app.terra.bio/#library/datasets/public/AMP%20PD.../data-explorer

Willy, can you also manually test the following:
- [one time setup] In local Terra, create a group called amp-pd-researchers. (This is to pass auth domain check.)
- In local Terra, from data library, go to AMP PD DE and save a cohort
- From Data tab, open cohort in DE. Confirm cohort is opened in same tab (as opposed to in a new tab)

2019-10-30 17:24 UTC, wnojopra commented on src/data/datasets.js
> +    origin: 'https://data-explorer.amp-pd.org',
Thanks!

@melissachang , when creating the amp-pd-researchers or amp-pd-clinical-access group on local Terra, I get a 409 error, "A resource of this type and name already exists". Is there a way around this?

And what do you think about this suggested change to getDataset in `workspace/Data.js` - we try to find the dataset by origin first, then by name. Something like:

```
  dataset = _.find({ origin: new URL(dataExplorerUrl).origin }, datasets)
  if (!dataset) {
    const datasetName = unescape(dataExplorerUrl.split(/datasets\/(?:public\/)?([^/]+)\/data-explorer/)[1])
    return _.find({ name: datasetName }, datasets)
  }
```

2019-10-30 17:35 UTC, melissachang commented on src/data/datasets.js
> +    origin: 'https://data-explorer.amp-pd.org',
That error is normal (in dev). If you refresh, you should see the group.

That change looks good to me. (Please keep the comments I had.) Please test with cohort from public DE, in addition to AMP PD DE. Thanks.

2019-10-30 17:50 UTC, wnojopra commented on src/data/datasets.js
> +    origin: 'https://data-explorer.amp-pd.org',
Great, thanks. Updated the code, and emailed you a screencast of the manual test.

2019-10-31 21:34 UTC, wnojopra commented
@panentheos @melissachang I believe I've addressed all the comments. Does the rest of the code look good to you?

2019-10-31 21:35 UTC, melissachang approved these changes
Sorry, didn't realize I was a reviewer

2019-11-01 17:42 UTC, mbookman commented
Thanks! Can this now be merged?

2019-11-01 17:49 UTC, melissachang commented
@panentheos still needs to approve

2019-11-04 14:27 UTC, panentheos approved these changes
Looks good.

2019-11-04 18:54 UTC, merged