lazily load snapshot contents [post- AS-577]
DataBiosphere/Saturn-UI pull request #2364
Opened 2021-01-15 21:39 UTC by Shakespeared

make snapshot contents load lazily, added ability to retry if a snapshot fails to load

2021-01-21 20:52 UTC, MatthewBemis approved these changes
LGTM. Tested locally by forcing a 4xx error loading snapshots

2021-01-25 17:24 UTC, davidangb requested changes

2021-01-25 17:24 UTC, davidangb commented on src/components/Collapse.js
> +  }, [firstOpenCallback, isOpened, refreshKey])
`useEffect` seems to be triggered every time I click on a snapshot table in the left nav. This means that `firstOpenCallback()` is called on every click, and thus the API call to `.../entities?...` occurs on every click.

Found by opening dev tools, watching network requests,  and clicking around on the tables.

2021-01-25 20:56 UTC, davidangb approved these changes
nice! Working well for me, tested locally.

2021-01-28 16:39 UTC, merged