Ky sup 498 pause from clusters page
DataBiosphere/Saturn-UI pull request #2611
Opened 2021-09-03 20:36 UTC by kyuksel

**Note for reviewers:** Experimenting with something new in hopes of easing PR reviewer burden 🤞🏼 

### Ticket
https://broadworkbench.atlassian.net/browse/SUP-498

### Screenshots
#### Dev
![image](https://user-images.githubusercontent.com/5438223/132062635-ff13d1c2-195d-4444-8fe4-1ac512946243.png)

#### PR Branch
![Screen Shot 2021-09-03 at 2 22 48 PM](https://user-images.githubusercontent.com/5438223/132062653-1cb6936c-1d30-46c1-ac50-d5cba09a1ffc.jpg)

### Highlights
- 

### Testing
- Locally deployed the changes and ran against dev backends

2021-09-07 17:17 UTC, rtitle commented
I tested a little bit, a few comments:

1. I feel like pause from the Cloud Environments page suffers from the "immediate feedback" problem. When I click pause nothing happens initially -- only after the page auto-refreshes ~10 seconds later do I see the status change to "Stopping". It feels like it'd be nicer to have the change reflected on the page immediately after click.

2. When a runtime or Galaxy is paused, I see a greyed-out Pause button. Should there be a Resume button instead?

3. I see a browser console warning when clicking pause:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at ComputeModalBase (http://localhost:3000/static/js/1.chunk.js:3510:25)
```

2021-09-07 17:19 UTC, rtitle requested changes
see comment above

2021-09-07 18:22 UTC, kyuksel commented on src/components/runtime-common.js
> +export const SaveFilesHelp = (isGalaxyDisk = false) => {
This wasn't part of my ticket but while testing my changes, I noticed that we are displaying a piece of message specific to Jupyter notebooks (from line#122 below) when Galaxy disk is to be deleted, and wanted to fix that as well.

2021-09-07 18:24 UTC, kyuksel commented on src/pages/Environments.js
`renderDeleteButton` replaces `renderDeleteButtonApps` and `renderDeleteButtonRuntimes` to reduce code duplication.

2021-09-07 18:25 UTC, kyuksel commented on src/pages/Environments.js
> -const Environments = ({ namespace }) => {
`namespace` wasn't being used

2021-09-07 19:02 UTC, kyuksel commented
Thanks for the testing @rtitle.

> 1. I feel like pause from the Cloud Environments page suffers from the "immediate feedback" problem. When I click pause nothing happens initially -- only after the page auto-refreshes ~10 seconds later do I see the status change to "Stopping". It feels like it'd be nicer to have the change reflected on the page immediately after click.

I agree. This exists in `dev` too but I'll see if I can improve it opportunistically.

> 2. When a runtime or Galaxy is paused, I see a greyed-out Pause button. Should there be a Resume button instead?

No, this ticket was scoped to only having the `pause` functionality. I agree though that it'd be nice to add a `resume` functionality at which time it'd make sense to have the button label and icons toggle between `pause` and `resume`.

> 3. I see a browser console warning when clicking pause
TL;DR: It's been a known situation and doesn't indicate a problem in our case. We have a wrapper around API calls that allows for setting a flag before and after making the API call. The one that's made after the API call triggers this warning because it happens after the component is unmounted. Since the flag we're updating isn't dependent on the component being mounted, it doesn't cause any issues for us.

2021-09-08 13:23 UTC, kyuksel commented
> I feel like pause from the Cloud Environments page suffers from the "immediate feedback" problem. When I click pause nothing happens initially -- only after the page auto-refreshes ~10 seconds later do I see the status change to "Stopping". It feels like it'd be nicer to have the change reflected on the page immediately after click.

@rtitle This issue should be resolved now. Upon clicking `Pause`, the UI will display the usual spinner while it gets a response from Leo. Upon receiving the response, the spinner will disappear and the tables will have updated values/button states.

2021-09-08 17:02 UTC, zarsky-broad approved these changes
Pending comments 👍

2021-09-08 17:02 UTC, zarsky-broad commented on src/libs/runtime-utils.js
> +const deletableStatuses = resourceType => Utils.switchCase(resourceType,
```js
export const isResourceDeletable = _.curry((resourceType, resource) => _.includes(_.capitalize(resource?.status),
  Utils.switchCase(resourceType,
    ['runtime', () => ['Unknown', 'Running', 'Updating', 'Error', 'Stopping', 'Stopped', 'Starting']],
    ['app', () => ['Unspecified', 'Running', 'Error']],
    ['disk', () => ['Failed', 'Ready']],
    [Utils.DEFAULT, () => console.error(`Resource type ${resourceType} is not one of runtime, app, or disk; deletability unknown`)]
  )
))

export const isComputePausable = _.curry((computeType, compute) => _.includes(_.capitalize(compute?.status),
  Utils.switchCase(computeType,
    ['runtime', () => ['Unknown', 'Running', 'Updating', 'Starting']],
    ['app', () => ['Running', 'Starting']],
    [Utils.DEFAULT, () => console.error(`Compute type ${computeType} is not one of runtime or app; pausability unknown`)]
  )
))
```

2021-09-08 17:02 UTC, zarsky-broad commented on src/pages/Environments.js
> +import { cond, formatUSD, makeCompleteDate, useCancellation, useGetter, useOnMount, usePollingEffect, withBusyState } from 'src/libs/utils'
Please call utils as `Utils.foo`

2021-09-08 17:02 UTC, zarsky-broad commented on src/pages/Environments.js
> +  const disabledButtonColorDarkness = colors.dark(0.4)
0.72 passes contrast; change default plz, file tix with ux

2021-09-08 17:02 UTC, zarsky-broad commented on src/pages/Environments.js
> +  })
```suggestion
  const pauseComputeAndRefresh = withBusyState(setLoading, async (computeType, compute) => {
    const wrappedPauseCompute = withErrorReporting('Error stopping compute', () => computeType === 'runtime' ?
      Ajax().Runtimes.runtime(compute.googleProject, compute.runtimeName).stop() :
      Ajax().Apps.app(compute.googleProject, compute.appName).pause())
    await wrappedPauseCompute()
    await loadData()
  })
```
but also wrap error more specifically for stop/pause

2021-09-08 17:02 UTC, zarsky-broad commented on src/pages/Environments.js
> +            field: 'actions',
```suggestion
```

2021-09-08 17:02 UTC, zarsky-broad commented on src/pages/Environments.js
> +              const computeType = cloudEnvironment.appName ? 'app' : 'runtime'
```suggestion
              const computeType = !!cloudEnvironment.appName ? 'app' : 'runtime'
```

2021-09-08 17:02 UTC, zarsky-broad commented on src/pages/Environments.js
> +                [status === 'Deleting', () => 'The disk is being deleted'],
```suggestion
                [status === 'Deleting', () => 'The disk is being deleted.'],
```

2021-09-09 12:49 UTC, rtitle approved these changes
Retested, looks good to me. Thanks for addressing my comments!

2021-09-09 14:21 UTC, merged