[SUP-558] Add filtering and sorting to call table in workflow dashboard
DataBiosphere/Saturn-UI pull request #3206
Opened 2022-07-07 15:17 UTC by MatthewBemis

<!--
Hello, friend!
Remember to mention what sort of testing/verification you performed in the course of building this PR, i.e. checking functionality in the browser locally.
Also, so if a screen recording [1] and/or screenshots would be a helpful way to communicate context, please consider including some in your PR description.
Thanks!

[1] https://support.apple.com/guide/quicktime-player/record-your-screen-qtp97b08e666/mac
--!>

2022-07-07 19:33 UTC, MatthewBemis commented on src/components/job-common.js
> +    whiteSpace: 'pre', textOverflow: 'ellipsis'
This was causing the status dropdown to become partially cut off when there were only a few rows. I don't believe that it has any adverse consequences

2022-07-07 19:38 UTC, MatthewBemis commented on src/pages/workspaces/workspace/jobHistory/CallTable.js
>              headerRenderer: () => 'Links',
I didn't think it was necessary to add a sort on the Links column

2022-07-07 19:57 UTC, nawatts requested changes
The bulk of the changes look good. Just one issue with the style change in `makeSection`.

2022-07-07 19:57 UTC, nawatts commented on src/components/job-common.js
> +    whiteSpace: 'pre', textOverflow: 'ellipsis'
This change affects the layout of the top section of the submission details page for some window sizes.

## Before
![Screen Shot 2022-07-07 at 3 48 09 PM](https://user-images.githubusercontent.com/1156625/177859715-063c4e09-859a-4825-bfde-c54dc990d9a8.png)

## After
![Screen Shot 2022-07-07 at 3 48 25 PM](https://user-images.githubusercontent.com/1156625/177859724-7eae4ef2-7999-4f16-a497-121cb669de2b.png)

2022-07-07 19:57 UTC, nawatts commented on src/components/job-common.js
> +    whiteSpace: 'pre', textOverflow: 'ellipsis'
Based on the 33% flex-basis in `makeSection`, I'm guessing it was designed for the top section of the workflow dashboard page ("Workflow Status", "Workflow Timing", and "Links"). I think we can replace it where it's used for the "Total Call Status Counts" and "Call Lists" sections.

2022-07-08 19:11 UTC, MatthewBemis commented on src/components/job-common.js
> +    whiteSpace: 'pre', textOverflow: 'ellipsis'
Fixed in 8c6988f726aadfd166fd8b901d8098f741dca636

It didn't seem possible to have the child override the `overflow` property of the parent, so I allowed overriding the style in `makeSection`

2022-07-08 20:41 UTC, nawatts approved these changes

2022-07-11 13:57 UTC, cjllanwarne approved these changes

2022-07-11 14:08 UTC, merged