[IA-3553] Re-enable testing on Dev PRs to accumulate more data for debugging
DataBiosphere/Saturn-UI pull request #3276
Opened 2022-07-28 16:52 UTC by xuscrbw

<!--
Hello, friend!
Remember to mention what sort of testing/verification you performed in the course of building this PR, i.e. checking functionality in the browser locally.
Also, so if a screen recording [1] and/or screenshots would be a helpful way to communicate context, please consider including some in your PR description.
Thanks!

[1] https://support.apple.com/guide/quicktime-player/record-your-screen-qtp97b08e666/mac
--!>

2022-07-28 17:00 UTC, Qi77Qi approved these changes
identity team released a fix that supposedly should improve Sam response time for getPet API...reenable test to see if it made any difference

2022-07-28 17:44 UTC, nawatts approved these changes

2022-08-17 18:56 UTC, nawatts requested changes

2022-08-17 18:56 UTC, nawatts commented on integration-tests/tests/run-analysis.js
> +  await delay(10000)
Is this waiting for the modal to close? 10 seconds seems like a long delay.

2022-08-17 18:56 UTC, nawatts commented on integration-tests/tests/run-analysis.js
> +  await delay(10000)
Is this delay necessary? If we need to wait longer, maybe increase the timeout on the next step instead of adding a delay?

2022-08-17 18:56 UTC, nawatts commented on integration-tests/tests/run-analysis.js
> +  //await noSpinnersAfter(page, { action: () => click(page, clickable({ text: 'Create' })) })
This can be removed.

2022-08-17 18:56 UTC, nawatts commented on integration-tests/tests/run-rstudio.js
> +  await delay(10000)
Similar comments as in the other file. Why are these long delays necessary? Commented out code can be removed.

2022-08-17 18:56 UTC, nawatts commented on integration-tests/tests/run-analysis.js
> +  await afterModalCollapse(page, {
`afterModalCollapse` is currently defined as:
```
const afterModalCollapse = async ({ action }) => {
  await Promise.all([action()])
  await delay(3000)
}
```

It only takes one parameter.

2022-08-17 18:56 UTC, nawatts commented on integration-tests/tests/run-rstudio.js
> +  //await noSpinnersAfter(page, { action: () => click(page, clickable({ text: 'Create' })) })
Commented out code can be removed.

2022-08-17 18:56 UTC, nawatts commented on integration-tests/utils/integration-utils.js
> +const afterModalCollapse = async ({ action }) => {
This function doesn't seem to have anything to do with a modal collapsing. Suggest removing it and directly awaiting whatever's passed as action.

2022-08-18 17:23 UTC, nawatts commented on integration-tests/tests/run-analysis.js
> +  await delay(3000)
It would be to add comments explaining why all these delays are necessary. What is not handled by the next step's timeout?

2022-08-22 14:34 UTC, nawatts requested changes

2022-08-22 14:34 UTC, nawatts commented on integration-tests/tests/analysis-context-bar.js
> +  targetEnvironments: ['dev']
`targetEnvironments: ['dev']` means this test will never be run. Integration tests against dev run with environment set to local.

https://github.com/DataBiosphere/terra-ui/blob/6dae7a5cbf8bb482e52aa1aceaf290c9e11366bf/.circleci/config.yml#L268-L274

2022-08-22 15:25 UTC, nawatts approved these changes

2022-08-22 15:25 UTC, nawatts commented on integration-tests/tests/run-analysis.js
> +  await delay(3000)
Does this work with a shorter delay? The transition on the ModalDrawer component is only 200ms.
https://github.com/DataBiosphere/terra-ui/blob/6dae7a5cbf8bb482e52aa1aceaf290c9e11366bf/src/components/ModalDrawer.js#L27-L32

2022-08-23 13:35 UTC, merged