Updated defaultDataprocWorkerDiskSize from 120 to 150.
DataBiosphere/Saturn-UI pull request #3322
Opened 2022-08-17 19:33 UTC by n8landolt

<!--
Hello, friend!
Remember to mention what sort of testing/verification you performed in the course of building this PR, i.e. checking functionality in the browser locally.
Also, so if a screen recording [1] and/or screenshots would be a helpful way to communicate context, please consider including some in your PR description.
Thanks!

[1] https://support.apple.com/guide/quicktime-player/record-your-screen-qtp97b08e666/mac
--!>

2022-08-17 19:59 UTC, Qi77Qi approved these changes
don't think this is needed unless automation tests proves otherwise

2022-08-17 20:16 UTC, Qi77Qi requested changes
the bug is that in UI, default worker size is 120, but it flips to 150 if user tries to update

A better fix will be not increasing worker size, but actually fixing the flip in UI

2022-08-17 20:23 UTC, Qi77Qi approved these changes
this is fine since Leo's worker disk size was bumped to 150 at some point (for whatever reason) https://github.com/DataBiosphere/leonardo/blob/develop/http/src/main/resources/reference.conf#L64

2022-08-19 15:27 UTC, cahrens approved these changes

2022-08-30 14:23 UTC, breilly2 approved these changes

2022-08-30 15:03 UTC, merged