[DC-627] Error logging follow-up
DataBiosphere/Saturn-UI pull request #3700
Opened 2023-01-19 17:52 UTC by fboulnois

Following up on conversations in https://github.com/DataBiosphere/terra-ui/pull/3652 , there are situations where just logging the response contents are not useful. Log both the object and response contents instead.

2023-01-19 17:53 UTC, nawatts approved these changes

2023-01-19 18:00 UTC, pshapiro4broad approved these changes

2023-01-20 03:35 UTC, nawatts requested changes
I did some more investigation into Puppeteer events and the objects passed to their callbacks.

https://pptr.dev/api/puppeteer.pageemittedevents
https://pptr.dev/api/puppeteer.pageeventobject/#properties

"error" and "pageerror" callbacks get Error objects. Thus, I'd expect the second thing logged here to always be "{}", which isn't useful. Thus, my preference would be to revert #3652.

```js
e = new Error('Something went wrong')
// Error: Something went wrong
//    at <anonymous>:1:5
e.toString()
// 'Error: Something went wrong'
JSON.stringify(e)
// '{}'
```

I was unable to find a way to get the original thrown object from the Error passed to the "pageerror" callback. I think if we want the response content of failed requests, we'll have to add it to the "response" event handler.

2023-01-20 15:10 UTC, nawatts requested changes

2023-01-20 15:10 UTC, nawatts commented on integration-tests/utils/integration-utils.js
> +  // this error will log an object of type [Error: Response] which is not very
Slight clarification... this happens only when our Ajax code throws a Response object after an error response from a request. For other types of errors, the output will be different.

2023-01-20 15:24 UTC, nawatts commented on integration-tests/utils/integration-utils.js
> +  // more useful but in fact this is the best we can do here since the object
I wouldn't say the object contents are empty. It seems that JSON.stringify doesn't work too well with Error objects.

For example, creating an error in the console. The error has properties, but JSON.stringify does not output them.
```js
const e = new Error('Something went wrong')

e.message
// 'Something went wrong'
e.stack
// 'Error: Something went wrong\n    at <anonymous>:1:11'

JSON.stringify(e)
// '{}'
```

2023-01-20 16:15 UTC, nawatts approved these changes

2023-01-20 16:58 UTC, nawatts commented
Also opened #3707 to log response content for error responses.

2023-01-20 17:59 UTC, merged