diskSize added, not multiplied
DataBiosphere/Saturn-UI pull request #3829
Opened 2023-03-01 22:26 UTC by lucymcnatt

2023-03-01 22:50 UTC, jdcanas approved these changes
Ah thanks, guess our tests weren't fully comprehensive in this case (or it was always a bug?). Do you think this is worth a test?

2023-03-02 00:25 UTC, sjacobs146 requested changes
It appears that we are still seeing "Unknown" for Hail Image before selecting Spark Cluster option and selecting Default image and compute type of Spark single node.

2023-03-02 17:13 UTC, mlilynolting commented on src/pages/workspaces/workspace/analysis/utils/cost-utils.ts
> +      getDefaultIfUndefined(config.workerDiskSize, defaultDataprocWorkerDiskSize)) *
wow

2023-03-02 17:20 UTC, mlilynolting approved these changes
LGTM - I think Susan's requested changes have been made; I can't recreate the buggily high prices for Spark clusters or the Unknown prices for Spark single node. ⭐️

2023-03-02 17:23 UTC, sjacobs146 approved these changes

2023-03-02 17:39 UTC, lucymcnatt commented
I can't approve cuz I opened it, but LGTM also

2023-03-02 18:00 UTC, merged