[IA-4126] Autopause UI for Azure runtimes
DataBiosphere/Saturn-UI pull request #3865
Opened 2023-03-23 17:41 UTC by mlilynolting

Setup Azure runtimes with autopause! Can enable/disable autopause on prospective runtimes, submit to create with the selected autopause value, and watch as after X minutes your runtime pauses. Opening an existing runtime shows a disabled autopause section with the existing value, if any, or the message "Autopause disabled." otherwise.

Todo unit tests. Behavior validated locally.

2023-03-23 18:06 UTC, n8landolt commented on src/pages/workspaces/workspace/analysis/modals/AzureComputeModal.js
> +  const updateComputeConfig = (key, value) => setComputeConfig({ ...computeConfig, [key]: value })
For other reviewers: I suggested this change - it's a bit easier to read and understand what's going on.

There's a bit of cleverness that goes on with _.set() that's additionally used in ComputeModal, which we will want to change as well.

2023-03-23 18:16 UTC, n8landolt commented on src/pages/workspaces/workspace/analysis/modals/ComputeModal.js
> +        // end Autopause component
I mislead you on this comment - the NumberInput component should be included as well

2023-03-29 14:26 UTC, n8landolt approved these changes

2023-03-29 14:28 UTC, n8landolt requested changes
Seems like starting from clicking "Open" is calling the wrong endpoint.

2023-03-30 15:08 UTC, n8landolt approved these changes

2023-04-05 13:15 UTC, LizBaldo approved these changes
Tested on my BEE and it looks good!

2023-04-05 13:32 UTC, merged