ImportAnalysis page, based on ImportData page.
DataBiosphere/Saturn-UI pull request #4088
Opened 2023-07-28 18:14 UTC by marikomedlock

### Jira Ticket: https://broadworkbench.atlassian.net/browse/[Ticket #]

## Summary of changes:

### What
Per advice from the `terra-ui` team [in Slack](https://broadinstitute.slack.com/archives/C01EHNUM73R/p1690551236395189), I added a new `ImportAnalysis` page that is based heavily on the existing `ImportData` page.

Once this PR is live in dev, I will add a companion change to Tanagra Data Explorer to redirect to `ImportAnalysis` when the user wants to export a notebook file to Community Workbench Terra.

### Why
The Tanagra Data Explorer ([gh repo](https://github.com/DataBiosphere/tanagra/), [project overview](https://broad.io/tanagra)) can generate an ipynb notebook file with the embedded SQL for a user's cohort. We want to let users import this file to Community Workbench Terra directly. This is a request from the DRC VUMC team who will use the first deployment of Tanagra.

Here is the general user flow I have in mind:
- User clicks "export notebook file" button in Tanagra Data Explorer.
- Tanagra Data Explorer generates a signed URL to an ipynb file.
- Tanagra Data Explorer redirects to a Community Workbench Terra import page.
- User chooses a workspace and clicks "import" button on Community Workbench Terra import page.
- Community Workbench Terra copies the notebook file to the workspace bucket, notebooks folder.
- Community Workbench Terra redirects to the workspaces page, analyses tab.

### Testing strategy
I added unit tests for the new page.

2023-07-28 18:40 UTC, marikomedlock commented on src/libs/events.js
> +  analysisImport: 'analysis:import',
I added a new event here, and see in the wiki that I'll also need to add it to the mixpanel lexicon. I should do this *after* merging the PR, is that correct?

2023-07-31 18:37 UTC, jdcanas commented on src/pages/ImportAnalysis.js
> +import _ from 'lodash/fp';
is there any reason not to introduce this new file as a typescript file? Seems pretty unsafe to introduce a javascript file when a lot of the underlying imports would be safer consumed with type checkcing

2023-07-31 18:37 UTC, jdcanas requested changes
Pretty against introducing new large files not as `.ts` files without a good reason

2023-07-31 18:40 UTC, jdcanas commented on src/pages/ImportAnalysis.js
> +    if (!isRuntimeToolLabel(runtime)) {
this seems pretty confusing. This method in particular would benefit from types. I'm guessing this `runtime` actually a `ToolLabel` and not a `Runtime`

2023-11-21 18:05 UTC, calypsomatic commented
@marikomedlock Just came across this PR and see that it is very old.  Is this still active/valid?

2023-11-22 13:35 UTC, marikomedlock commented
> @marikomedlock Just came across this PR and see that it is very old. Is this still active/valid?

No, product decided not to pursue this feature.

2023-11-22 13:35 UTC, closed without merging