[WIP] Extract Select component
DataBiosphere/Saturn-UI pull request #4653
Opened 2024-02-09 21:26 UTC by NehaBroad

### Jira Ticket: https://broadworkbench.atlassian.net/browse/[Ticket #]

## Summary of changes:

### What
- 

### Why
- 

### Testing strategy
- [ ]

2024-02-09 21:59 UTC, nawatts requested changes

2024-02-09 21:59 UTC, nawatts commented on packages/components/src/Select.ts
We've recently (#4637) intentionally removed react-hyperscript-helpers from this package. This component would need to be updated to use JSX.

2024-02-09 21:59 UTC, nawatts commented on packages/components/src/Select.ts
> +let colors: any;
Can we find a better way than a global variable to pass the colors from the theme context through to React Select's theme?

2024-02-09 21:59 UTC, nawatts commented on packages/components/src/hooks/useOnMount.ts
My experience with this function is that it almost always results in a bug. I'm very opposed to promoting it to the components package. It doesn't look like it's required for this PR, but if so, it should be replaced with `useEffect`, where we get the benefit of ESLint checking the dependencies list.

2024-02-12 17:36 UTC, NehaBroad commented
Thank you @nawatts ! I am going to close this PR, this was just a test to see if i can open a PR as i did not have permissions. Its still WIP i'll re-open this with final changes

2024-02-12 17:36 UTC, closed without merging