[AJ-1277] select and delete rows
DataBiosphere/Saturn-UI pull request #5090
Opened 2024-09-18 15:34 UTC by mspector

### Jira Ticket: https://broadworkbench.atlassian.net/browse/[Ticket #]

## Summary of changes:

### What
-

### Why
-

### Testing strategy

- [ ]

2024-09-20 21:03 UTC, kevinmarete requested changes

2024-09-20 21:03 UTC, kevinmarete commented on src/libs/ajax/WorkspaceDataService.ts
> +      `records/v1/${collectionId}/${recordType}`,
```suggestion
      `records/v1/${collectionId}/${recordType}/delete`,
```
Update URL to this since I am getting a 404
<img width="1792" alt="Screenshot 2024-09-20 at 4 24 40 PM" src="https://github.com/user-attachments/assets/8bbdf395-5dc8-4f40-a00d-3992f69d51f2">

2024-09-20 21:03 UTC, kevinmarete commented on src/workspace-data/data-table/wds/WDSContent.ts
> +          Ajax().Metrics.captureEvent(Events.workspaceDataDelete, extractWorkspaceDetails(workspace.workspace));
I like that we are capturing the deletion event

2024-09-20 21:03 UTC, kevinmarete commented on src/workspace-data/data-table/wds/RecordDeleter.js
> +
Add a new function `filterAdditionalDeletions` to ensure the logic is testable independently. 

```suggestion

const filterAdditionalDeletions = async (error: Response, recordsToDelete: Array<{ entityType: string, entityName: string }>) => {
  const errorEntities = await error.json();
  
  return _.filter(errorEntities, (errorEntity: { entityType: string, entityName: string }) => 
    !_.some(recordsToDelete, (selectedEntity) => 
      selectedEntity.entityType === errorEntity.entityType && selectedEntity.entityName === errorEntity.entityName
    )
  );
};
```

2024-09-20 21:03 UTC, kevinmarete commented on src/workspace-data/data-table/wds/RecordDeleter.js
> +          onDismiss();
Sonarcloud suggested removing the switch case: _"switch" statements should have at least 3 "case" clauses_
Use the new function `filterAdditionalDeletions` added above in your implementation

```suggestion
      if (error.status != 409){
         await reportError('Error deleting data entries', error);
         return onDismiss();
      }
          
      // Handle 409 error by filtering additional deletions that need to be deleted first
      setAdditionalDeletions(await filterAdditionalDeletions(error, recordsToDelete));
      setDeleting(false);
```

2024-09-23 16:47 UTC, davidangb commented on src/libs/ajax/data-table-providers/WdsDataTableProvider.ts
> +      supportsRowSelection: true,
with this set to true, we render the "select all" option in the data table. Selecting that option causes an error for WDS-powered data tables.

2024-09-30 13:22 UTC, calypsomatic commented on src/workspace-data/data-table/wds/RecordDeleter.js
> +export const RecordDeleter = ({ onDismiss, onSuccess, dataProvider, collectionId, selectedRecords, runningSubmissionsCount }) => {
Any particular reason why this is `.js` instead of `.ts`?  I'd love for new files to be `.ts` so we don't have to convert them later!

2024-09-30 13:27 UTC, calypsomatic commented on src/workspace-data/data-table/wds/RecordDeleter.js
> +      // Handle 409 error by filtering additional deletions that need to be deleted first
Is this in case of references?  Or why would they need to be deleted first?

2024-09-30 13:28 UTC, calypsomatic commented on src/workspace-data/data-table/wds/RecordDeleter.js
> +  const total = selectedKeys.length + additionalDeletions.length;
Should this `additionalDeletions` also be checked with `!!`?

2024-09-30 13:46 UTC, calypsomatic commented
If I run this branch against your `AJ-1277_delete-records-capabilities` WDS branch, I get an error when I try to delete a record - on WDS's end it shows that it gets the request with no errors, but the response returned to the UI is `{
  "error": "Bad Request",
  "message": "Failed to read request",
  "status": 400,
  "timestamp": "2024-09-30T13:39:57.320+00:00",
  "path": "/records/v1/f6f984a9-3bbe-48b9-9389-bf73f8d2f558/primary/delete"
}`.  Is there something further I need to do to get this set up to work?

2024-09-30 14:24 UTC, calypsomatic commented
Ok I think there's a mismatch between the format of the deleteRecordsRequest in the front end and backend.  In the backend, everything is camel case: `recordIds`, front-end is snake cake: `record_ids`.  But once I changed that there were still problems: `recordIds` should be a list of strings, the record ids, but the front end is passing in a list of objects with keys `entityName` and `entityType`.

2024-10-21 14:25 UTC, closed without merging